// ============================================================
// Server-Side Mock Data (Stub)
// ============================================================
// Temporary data used until the MySQL connection is wired up.
// Mirrors the shape of the posts endpoint response so the API
// can return realistic data during local development.
// ============================================================

import type { Category, Post, User } from "../types";

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "技术",
    description: "开发与数据",
    icon: "⌘",
    parent_id: null,
    sort_order: 1,
    is_active: 1,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: 2,
    name: "AI",
    description: "AI 产品与工具",
    icon: "✦",
    parent_id: null,
    sort_order: 2,
    is_active: 1,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: 3,
    name: "设计",
    description: "视觉与创意",
    icon: "▣",
    parent_id: null,
    sort_order: 3,
    is_active: 1,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: 4,
    name: "学习",
    description: "学习服务",
    icon: "Aa",
    parent_id: null,
    sort_order: 4,
    is_active: 1,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: 5,
    name: "求职",
    description: "简历与作品集",
    icon: "◈",
    parent_id: null,
    sort_order: 5,
    is_active: 1,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: 6,
    name: "二手",
    description: "校园闲置",
    icon: "↗",
    parent_id: null,
    sort_order: 6,
    is_active: 1,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: 7,
    name: "校园",
    description: "校园生活",
    icon: "→",
    parent_id: null,
    sort_order: 7,
    is_active: 1,
    created_at: "2025-01-01T00:00:00.000Z",
  },
];

export const mockUsers: User[] = [
  {
    user_id: 1,
    nickname: "MIA_Ether",
    avatar: null,
    anonymous_name: null,
    phone: null,
    email: null,
    role: 0,
    is_verified: 0,
    status: 1,
    created_at: "2025-01-01T00:00:00.000Z",
    updated_at: "2025-01-01T00:00:00.000Z",
  },
];

export const mockPosts: Post[] = [
  {
    id: 1,
    user_id: 1,
    category_id: 1,
    title: "Python / SQL Debug",
    content: "Python、SQL、数据处理、环境配置与常见报错排查。",
    images: [],
    price: "¥20 起",
    is_anonymous: 0,
    status: 1,
    views: 24,
    like_count: 3,
    favorite_count: 1,
    comment_count: 0,
    created_at: "2025-01-15T10:30:00.000Z",
    updated_at: "2025-01-15T10:30:00.000Z",
  },
  {
    id: 2,
    user_id: 1,
    category_id: 2,
    title: "AI Workflow Pack",
    content: "常用 AI 工作流、Prompt 与自动化模板合集。",
    images: [],
    price: "¥9.9",
    is_anonymous: 0,
    status: 1,
    views: 48,
    like_count: 5,
    favorite_count: 2,
    comment_count: 1,
    created_at: "2025-01-14T14:00:00.000Z",
    updated_at: "2025-01-14T14:00:00.000Z",
  },
  {
    id: 3,
    user_id: 1,
    category_id: 5,
    title: "Portfolio Review",
    content: "个人网站、作品集与项目介绍的结构优化。",
    images: [],
    price: "¥29 起",
    is_anonymous: 0,
    status: 1,
    views: 12,
    like_count: 1,
    favorite_count: 0,
    comment_count: 0,
    created_at: "2025-01-13T09:00:00.000Z",
    updated_at: "2025-01-13T09:00:00.000Z",
  },
];
